apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workflow-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "workflow-app.labels" . | nindent 4 }}
data:
  CHROMA_PATH: {{ .Values.backend.env.chromaPath | quote }}
  POSTGRES_HOST: "{{ include "workflow-app.fullname" . }}-postgres"
  POSTGRES_PORT: "5432"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
